""" updating announcements

Revision ID: eda55a6639c9
Revises: 97e352cffe21
Create Date: 2026-08-31 22:54:19.019083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda55a6639c9'
down_revision = '97e352cffe21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_popup', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('is_popup')

    # ### end Alembic commands ###
